DATASET: 'CustomDataset'
# DATA_PATH: '../data/custom'
DATA_PATH: '/mnt/nas3/Data/PCD/indoor_parking/config_test/custom'
# /mnt/nas3/Data/PCD/indoor_parking/config_test/custom
# DATA_PATH: '/mnt/nas3/Data/PCD/indoor_parking/generalization_test/custom'

# CLASS_NAMES: ['', '', '', '', '', '', '', '', '']
    # class_to_name = {
    #     0: 'Car',
    #     1: 'Pedestrian',
    #     2: 'Cyclist',
    #     3: 'Van',
    #     4: 'Person_sitting',
    #     5: 'Truck'
    # }
# POINT_CLOUD_RANGE: [-75.2, -75.2, -2, 75.2, 75.2, 4]
POINT_CLOUD_RANGE: [-75.2, -75.2, -2, 75.2, 75.2, 4]

# name classes           car  ped  cyc  van  per  tru  mast
# int classes:            0    1    2    3    4    5    6
# MAP_CLASS_TO_KITTI: {
#     'Vehicle': 'Car',
#     'Human': 'Pedestrian',
#     'Traffic_Cone': 'Pedestrian',
#     'Pillar': 'Pedestrian',
#     'Wheelchair': 'Person_sitting',
#     'Stroller': 'Person_sitting',
#     'Two_Wheeled_Vehicle':'Cyclist',
#     'Shopping_Cart': 'Person_sitting',
#     'Tow_Wheeled_Vehicle':'Pedestrian'
# }
MAP_CLASS_TO_KITTI: {
    'Vehicle': 'Vehicle',
    'Human': 'Human',
    # 'Wheelchair' : 'Cyclist',
    # 'Stroller': 'Person_sitting',
    # 'Two_Wheeled_Vehicle':'Cyclist',
    # 'Traffic_Cone': 'Cyclist',
    # 'Shopping_Cart': 'Person_sitting',
    # 'Pillar': 'Cyclist',
    # 'Tow_Wheeled_Vehicle':'Pedestrian',
}

# ['Human',
#  'Wheelchair',
#  'Vehicle',
#  'Stroller',
#  'Pillar',
#  'Two_Wheeled_Vehicle',
#  'Traffic_Cone',
#  'Shopping_Cart']

DATA_SPLIT: {
    'train': train,
    'test': val
}

INFO_PATH: {
    'train': [custom_infos_train.pkl],
    'test': [custom_infos_val.pkl],
}

POINT_FEATURE_ENCODING: {
    encoding_type: absolute_coordinates_encoding,
    used_feature_list: ['x', 'y', 'z', 'intensity'],
    src_feature_list: ['x', 'y', 'z', 'intensity'],
}

DATA_AUGMENTOR:
    DISABLE_AUG_LIST: ['placeholder']
    AUG_CONFIG_LIST:
        - NAME: gt_sampling
          USE_ROAD_PLANE: False
          DB_INFO_PATH:
              - custom_dbinfos_train.pkl
          # PREPARE: {
          #    filter_by_min_points: ['Vehicle:5', 'Pedestrian:5', 'Cyclist:5'],
          # }
          PREPARE: {
            filter_by_min_points: ['Vehicle:5'],

            # filter_by_min_points: ['Vehicle:5', 'Human:5', 'Wheelchair:5'],
            #  filter_by_min_points:  ['Human:5', 'Wheelchair:5', 'Vehicle:5', 'Stroller:5', 'Pillar:5', 'Two_Wheeled_Vehicle:5', 'Traffic_Cone:5', 'Shopping_Cart:5', 'Tow_Wheeled_Vehicle:5'],
            #  filter_by_min_points: ['Pillar:5', 'Vehicle:5', 'Traffic_Cone:5','Human:5'],
            # filter_by_min_points:  ['Human:3', 'Wheelchair:3', 'Vehicle:3', 'Stroller:3', 'Pillar:3', 'Two_Wheeled_Vehicle:3', 'Traffic_Cone:3', 'Shopping_Cart:3'],
          }
          SAMPLE_GROUPS: ['Vehicle:5']

          # SAMPLE_GROUPS: ['Vehicle:5', 'Human:10', 'Wheelchair:15']
          # SAMPLE_GROUPS: ['Human:5', 'Wheelchair:10', 'Vehicle:15', 'Stroller:10', 'Pillar:20', 'Two_Wheeled_Vehicle:10', 'Traffic_Cone:25', 'Shopping_Cart:10', 'Tow_Wheeled_Vehicle:10']
          # SAMPLE_GROUPS: ['Pillar:20', 'Vehicle:15', 'Traffic_Cone:10','Human:5']
          # SAMPLE_GROUPS: ['Human:5', 'Wheelchair:10', 'Vehicle:15', 'Stroller:10', 'Pillar:20', 'Two_Wheeled_Vehicle:10', 'Traffic_Cone:25', 'Shopping_Cart:10']

          NUM_POINT_FEATURES: 4
          DATABASE_WITH_FAKELIDAR: False
          REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
          LIMIT_WHOLE_SCENE: True

        - NAME: random_world_flip
          ALONG_AXIS_LIST: ['x', 'y']

        - NAME: random_world_rotation
          WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]

        - NAME: random_world_scaling
          WORLD_SCALE_RANGE: [0.95, 1.05]

DATA_PROCESSOR:
    - NAME: mask_points_and_boxes_outside_range
      REMOVE_OUTSIDE_BOXES: True

    - NAME: shuffle_points
      SHUFFLE_ENABLED: {
        'train': True,
        'test': False
      }

    - NAME: transform_points_to_voxels
      VOXEL_SIZE: [0.1, 0.1, 0.15]
      MAX_POINTS_PER_VOXEL: 5
      MAX_NUMBER_OF_VOXELS: {
        'train': 150000,
        'test': 150000
      }